### ISSUE TITLE
Прочитать основания конкурса и составить заявку 

### ISSUE THREAD

**Issue by Takunava** [Takunava/arduino#2]
1) Вся документация лежит в конфе по ардуино (https://vk.me/join/AJQ1d4zRYRN96D5Xuive_qzv)
2) Постараться не накосячить при составлении заявки
3) Срок подачи заявки 9 декабря

**Comment by nrabotko** [comment]
Добрый день.
Ссылка на регистрацию и расположение положения конкурса.

**Comment by Takunava** [comment]
Здравствуйте
Спам
Спасибо

**Comment by nrabotko** [comment]
Добрый день.
Предоставляю [Положение конкурс роботехники - 2019.pdf](https://github.com/Takunava/arduino/files/3931612/-.2019.pdf).

**Comment by nrabotko** [comment]
Сегодня отправили заявку на участие в конкурсе.
[Заявка.pdf](https://github.com/Takunava/arduino/files/3938470/default.pdf)
