### ISSUE TITLE
Зарегистрироваться на мероприятие в LiderID

### ISSUE THREAD

**Issue by Takunava** [Takunava/arduino#5]
Ссылка на регистрацию и расположение положения конкурса.
[LeaderID](https://leader-id.ru/event/36805/)

**Comment by Takunava** [comment]
Зарегистрировался

**Comment by Pipyao** [comment]
Зарегался

**Comment by AndreiDevyaterikov** [comment]
Зарегистрировался

**Comment by nrabotko** [comment]
Зарегистрировалась
![1](https://user-images.githubusercontent.com/47633682/70418525-9e256200-1a74-11ea-9e74-4a0631f7b7a8.png)
